INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (1, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (2, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (3, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (4, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (5, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (6, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (7, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (8, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (9, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (10, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (11, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (12, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (13, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (14, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (15, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (16, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (17, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (18, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (19, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (20, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (21, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (22, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (23, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (24, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (25, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (26, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (27, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (28, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (29, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (30, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (31, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (32, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (33, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (34, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (35, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (36, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (37, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (38, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (39, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (40, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (41, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (42, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (43, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (44, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (45, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (46, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (47, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (48, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (49, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (50, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (51, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (52, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (53, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (54, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (55, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (56, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (57, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (58, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (59, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (60, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (61, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (62, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (63, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (64, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (65, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (66, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (67, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (68, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (69, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (70, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (71, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (72, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (73, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (74, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (75, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (76, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (77, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (78, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (79, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (80, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (81, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (82, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (83, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (84, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (85, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (86, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (87, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (88, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (89, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (90, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (91, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (92, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (93, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (94, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (95, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (96, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (97, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (98, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (99, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (100, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (101, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (102, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (103, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (104, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (105, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (106, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (107, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (108, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (109, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (110, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (111, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (112, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (113, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (114, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (115, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (116, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (117, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (118, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (119, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (120, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (121, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (122, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (123, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (124, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (125, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (126, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (127, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (128, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (129, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (130, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (131, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (132, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (133, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (134, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (135, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (136, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (137, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (138, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (139, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (140, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (141, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (142, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (143, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (144, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (145, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (146, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (147, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (148, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (149, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (150, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (151, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (152, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (153, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (154, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (155, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (156, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (157, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (158, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (159, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (160, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (161, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (162, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (163, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (164, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (165, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (166, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (167, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (168, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (169, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (170, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (171, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (172, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (173, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (174, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (175, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (176, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (177, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (178, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (179, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (180, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (181, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (182, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (183, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (184, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (185, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (186, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (187, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (188, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (189, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (190, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (191, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (192, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (193, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (194, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (195, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (196, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (197, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (198, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (199, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (200, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (201, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (202, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (203, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (204, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (205, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (206, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (207, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (208, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (209, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (210, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (211, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (212, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (213, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (214, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (215, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (216, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (217, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (218, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (219, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (220, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (221, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (222, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (223, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (224, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (225, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (226, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (227, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (228, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (229, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (230, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (231, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (232, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (233, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (234, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (235, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (236, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (237, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (238, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (239, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (240, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (241, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (242, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (243, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (244, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (245, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (246, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (247, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (248, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (249, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (250, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (251, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (252, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (253, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (254, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (255, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (256, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (257, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (258, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (259, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (260, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (261, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (262, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (263, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (264, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (265, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (266, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (267, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (268, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (269, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (270, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (271, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (272, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (273, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (274, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (275, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (276, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (277, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (278, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (279, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (280, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (281, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (282, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (283, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (284, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (285, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (286, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (287, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (288, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (289, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (290, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (291, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (292, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (293, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (294, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (295, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (296, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (297, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (298, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (299, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (300, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (301, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (302, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (303, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (304, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (305, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (306, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (307, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (308, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (309, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (310, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (311, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (312, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (313, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (314, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (315, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (316, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (317, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (318, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (319, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (320, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (321, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (322, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (323, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (324, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (325, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (326, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (327, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (328, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (329, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (330, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (331, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (332, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (333, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (334, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (335, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (336, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (337, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (338, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (339, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (340, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (341, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (342, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (343, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (344, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (345, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (346, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (347, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (348, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (349, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (350, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (351, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (352, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (353, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (354, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (355, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (356, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (357, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (358, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (359, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (360, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (361, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (362, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (363, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (364, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (365, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (366, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (367, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (368, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (369, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (370, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (371, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (372, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (373, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (374, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (375, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (376, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (377, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (378, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (379, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (380, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (381, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (382, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (383, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (384, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (385, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (386, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (387, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (388, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (389, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (390, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (391, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (392, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (393, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (394, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (395, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (396, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (397, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (398, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (399, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (400, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (401, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (402, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (403, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (404, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (405, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (406, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (407, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (408, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (409, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (410, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (411, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (412, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (413, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (414, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (415, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (416, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (417, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (418, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (419, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (420, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (421, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (422, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (423, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (424, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (425, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (426, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (427, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (428, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (429, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (430, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (431, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (432, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (433, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (434, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (435, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (436, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (437, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (438, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (439, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (440, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (441, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (442, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (443, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (444, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (445, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (446, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (447, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (448, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (449, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (450, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (451, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (452, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (453, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (454, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (455, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (456, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (457, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (458, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (459, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (460, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (461, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (462, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (463, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (464, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (465, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (466, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (467, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (468, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (469, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (470, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (471, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (472, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (473, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (474, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (475, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (476, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (477, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (478, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (479, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (480, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (481, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (482, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (483, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (484, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (485, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (486, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (487, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (488, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (489, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (490, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (491, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (492, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (493, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (494, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (495, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (496, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (497, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (498, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (499, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (500, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (501, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (502, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (503, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (504, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (505, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (506, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (507, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (508, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (509, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (510, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (511, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (512, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (513, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (514, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (515, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (516, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (517, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (518, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (519, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (520, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (521, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (522, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (523, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (524, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (525, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (526, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (527, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (528, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (529, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (530, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (531, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (532, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (533, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (534, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (535, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (536, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (537, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (538, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (539, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (540, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (541, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (542, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (543, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (544, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (545, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (546, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (547, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (548, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (549, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (550, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (551, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (552, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (553, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (554, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (555, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (556, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (557, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (558, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (559, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (560, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (561, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (562, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (563, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (564, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (565, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (566, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (567, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (568, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (569, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (570, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (571, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (572, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (573, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (574, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (575, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (576, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (577, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (578, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (579, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (580, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (581, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (582, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (583, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (584, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (585, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (586, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (587, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (588, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (589, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (590, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (591, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (592, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (593, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (594, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (595, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (596, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (597, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (598, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (599, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (600, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (601, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (602, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (603, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (604, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (605, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (606, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (607, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (608, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (609, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (610, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (611, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (612, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (613, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (614, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (615, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (616, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (617, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (618, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (619, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (620, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (621, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (622, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (623, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (624, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (625, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (626, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (627, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (628, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (629, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (630, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (631, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (632, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (633, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (634, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (635, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (636, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (637, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (638, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (639, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (640, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (641, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (642, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (643, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (644, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (645, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (646, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (647, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (648, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (649, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (650, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (651, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (652, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (653, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (654, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (655, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (656, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (657, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (658, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (659, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (660, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (661, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (662, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (663, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (664, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (665, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (666, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (667, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (668, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (669, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (670, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (671, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (672, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (673, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (674, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (675, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (676, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (677, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (678, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (679, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (680, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (681, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (682, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (683, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (684, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (685, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (686, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (687, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (688, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (689, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (690, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (691, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (692, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (693, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (694, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (695, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (696, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (697, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (698, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (699, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (700, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (701, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (702, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (703, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (704, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (705, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (706, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (707, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (708, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (709, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (710, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (711, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (712, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (713, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (714, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (715, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (716, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (717, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (718, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (719, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (720, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (721, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (722, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (723, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (724, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (725, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (726, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (727, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (728, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (729, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (730, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (731, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (732, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (733, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (734, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (735, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (736, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (737, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (738, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (739, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (740, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (741, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (742, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (743, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (744, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (745, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (746, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (747, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (748, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (749, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (750, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (751, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (752, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (753, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (754, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (755, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (756, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (757, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (758, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (759, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (760, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (761, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (762, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (763, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (764, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (765, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (766, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (767, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (768, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (769, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (770, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (771, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (772, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (773, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (774, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (775, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (776, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (777, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (778, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (779, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (780, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (781, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (782, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (783, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (784, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (785, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (786, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (787, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (788, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (789, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (790, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (791, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (792, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (793, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (794, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (795, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (796, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (797, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (798, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (799, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (800, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (801, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (802, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (803, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (804, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (805, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (806, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (807, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (808, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (809, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (810, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (811, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (812, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (813, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (814, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (815, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (816, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (817, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (818, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (819, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (820, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (821, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (822, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (823, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (824, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (825, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (826, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (827, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (828, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (829, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (830, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (831, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (832, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (833, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (834, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (835, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (836, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (837, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (838, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (839, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (840, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (841, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (842, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (843, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (844, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (845, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (846, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (847, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (848, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (849, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (850, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (851, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (852, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (853, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (854, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (855, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (856, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (857, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (858, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (859, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (860, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (861, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (862, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (863, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (864, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (865, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (866, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (867, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (868, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (869, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (870, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (871, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (872, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (873, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (874, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (875, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (876, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (877, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (878, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (879, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (880, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (881, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (882, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (883, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (884, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (885, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (886, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (887, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (888, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (889, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (890, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (891, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (892, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (893, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (894, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (895, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (896, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (897, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (898, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (899, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (900, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (901, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (902, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (903, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (904, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (905, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (906, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (907, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (908, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (909, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (910, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (911, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (912, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (913, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (914, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (915, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (916, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (917, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (918, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (919, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (920, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (921, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (922, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (923, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (924, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (925, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (926, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (927, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (928, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (929, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (930, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (931, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (932, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (933, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (934, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (935, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (936, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (937, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (938, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (939, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (940, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (941, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (942, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (943, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (944, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (945, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (946, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (947, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (948, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (949, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (950, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (951, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (952, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (953, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (954, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (955, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (956, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (957, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (958, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (959, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (960, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (961, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (962, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (963, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (964, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (965, 'Credit card');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (966, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (967, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (968, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (969, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (970, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (971, 'Ewallet');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (972, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (973, 'Cash');
INSERT INTO public.payment_dimension (payment_id, payment_method) VALUES (974, 'Cash');
